# Generated by Django 5.0.3 on 2024-03-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebel',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=62),
        ),
    ]
